name: Build, Test & Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein with-profile test deps
      - name: Run tests
        run: lein test
      - name: Deploy
        run: lein deploy github || true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}