name: Build, Test & Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein test
      - name: Deploy
        run: lein deploy github
        env:
          GITHUB_TOKEN: {{secrets.GITHUB_TOKEN}}