name: Docker Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: manusa/actions-publish-docker@master
      with:
        name: docker.pkg.github.com/piperswe/lake/lake
        username: piperswe
        password: ${{secrets.GITHUB_TOKEN}}
