name: test-suite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein with-profile test deps
      - name: Run tests
        run: lein test
