name: test-suite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein with-profile test deps
      - name: Run tests
        run: lein test
      - name: Build jar
        run: lein uberjar
      - uses: actions/upload-artifact@v1
        with:
          name: lake-standalone.jar
          path: target/lake-*-standalone.jar
